name: CI

on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-lastest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: node-modules-${{ hashFiles('yarn.lock') }}
    - name: Install modules
    if: steps.cache.outputs.cache-hit != 'true'
      run: yarn cache clean && yarn install --network-concurrency 1
    - name: Run ESLint
    run: yarn lint
